name: Puppeteer tests
on: push

jobs:
  build:
    name: Puppeteer tests
    # Tell the action to use the latest
    # version of Ubuntu (a Linux flavor)
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    env:
      PGHOST: localhost
      PGPORT: 5432
      PGDATABASE: next_js_example_jan_2022
      PGUSERNAME: next_js_example_jan_2022
      PGPASSWORD: next_js_example_jan_2022
    steps:
      # Use preinstalled PostgreSQL
      - name: Start PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready
      # Change user name and password to meet your requirements
      - name: Create additional user
        run: |
          sudo -u postgres psql --command="CREATE USER next_js_example_jan_2022 PASSWORD 'next_js_example_jan_2022'" --command="\du"
      # Change database name to meet your requirements
      - name: Create additional database
        run: |
          sudo -u postgres createdb --owner=next_js_example_jan_2022 next_js_example_jan_2022
      # Use the official Checkout action (clones the GitHub repo):
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
      # Use the official setup-node action (sets up Node.js):
      # https://github.com/actions/setup-node
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
      # Build the Next.js application
      - run: yarn build
      # Run the Jest unit tests
      - run: yarn jest --config integration/jest.config.mjs
